  # Ansible playbook for install docker image from Docker Hub to AWS EC2
---
- name: EC2 install docker
  hosts: ec2_servers
  become: yes

  tasks:
    - name: Update all AWS-linux packages
      yum:
        name: '*'
        update_only: yes

    - name: Ensure a list of yum packages are installed
      yum:
        name: "{{ packages }}"
        state: latest
        update_cache: yes
      vars:
        packages:
          - python-pip
          - yum-utils
          - amazon-linux-extras
          - lvm2

    - name: Add amazon-linux-extras repository
      shell: yum-config-manager --enable extras

    - name: Enable some packages from amazon-linux-extras packages
      shell: "amazon-linux-extras enable python3.8 ansible2 docker"

    - name: clean yum metadata cache
      command: yum clean metadata
      args:
        warn: false

    - name: Ensure a list of yum packages are installed
      yum:
        name: "{{ packages }}"
        state: latest
        update_cache: yes
      vars:
        packages:
          - python3.8
          - ansible
          - docker

    - name: Enable Docker CE service at startup
      service:
        name: docker
        state: started
        enabled: yes

    - name: Pull Docker image from DockerHub
      command: docker pull bobururinboev/my-docker-images:docker-flask

    - name: Build Docker container out of image
      command: docker run -dp 5000:5000 bobururinboev/my-docker-images:docker-flask

